#!/usr/bin/python

import SimpleHTTPServer
import SocketServer
import os

class Test(SimpleHTTPServer.SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/ant_debug":
            os.system("cd test && ant debug")
            self.path = "/index.html"

        return SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET(self)

SocketServer.TCPServer.allow_reuse_address = True
server = SocketServer.TCPServer(('0.0.0.0', 80), Test)
server.serve_forever()
