#!/bin/sh

if [ $# -eq 0 ]; then
	echo 'Usage: '$0' [key]'
	echo ''
	exit
fi

key=$1

echo 'package appm.'$key';'
echo ''
echo 'import android.os.Bundle;'
echo 'import org.apache.cordova.*;'
echo ''
echo 'public class appm extends DroidGap'
echo '{'
echo '    @Override'
echo '    public void onCreate(Bundle savedInstanceState)'
echo '    {'
echo '        super.onCreate(savedInstanceState);'
echo '        super.loadUrl(Config.getStartUrl());'
echo '    }'
echo '}'
